name: install-cosign-and-use
on:
  # This will trigger the workflow to run when commits are pushed to the main branch.
  # This is easy for testing purposes, but for your final workflow use whatever event 
  # or schedule makes sense for your project.
   push:
    branches: [ main ]
jobs:
  install-cosign-and-use:
    name: Install Cosign
    runs-on: ubuntu-latest
    # No special permissions are required to install cosign, but `id-token: write` is needed to sign with your workflow identity.
    permissions:
       id-token: write
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Check install!
        run: cosign version
