name: install-and-check-cosign
on:
   push:
    branches: [ main ]
permissions:
  id-token: write # needed for signing the images with GitHub OIDC Token

jobs:
  install-and-check-cosign:
    name: Install Cosign
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Check install!
        run: cosign version
      - name: Import project
        uses: actions/checkout@v3
      - name: Sign the images with GitHub OIDC Token
        run: cosign sign-blob README.md --bundle cosign.bundle --yes
