name: understanding-ci
on:
   push:
    branches: [ main ]
permissions: read-all

jobs:
  understanding-ci:
    name: Install Cosign
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Check install!
        run: cosign version
