name: install-and-check-cosign
on: workflow_dispatch
permissions:
  id-token: write # needed for signing with GitHub OIDC Token

jobs:
  install-and-check-cosign:
    name: Install Cosign
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Check install!
        run: cosign version
      - name: Import project
        uses: actions/checkout@v3
      - name: Verify blob
        run: cosign verify-blob README.md --bundle cosign.bundle --certificate-identity=https://github.com/hayleycd/sigstore_experiment/.github/workflows/cosign-experiment.yml@refs/heads/main --certificate-oidc-issuer=https://token.actions.githubusercontent.com
