name: verify
on: workflow_dispatch
permissions:
  id-token: write # needed for signing with GitHub OIDC Token

jobs:
  verify:
    name: Install Cosign
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Check install!
        run: cosign version
      - name: Import project
        uses: actions/checkout@v3
      - name: Verify blob
        run: cosign verify-blob README.md --bundle cosign.bundle --certificate-identity=cook.hayley@gmail.com --certificate-oidc-issuer=https://github.com/login/oauth
